services:
  batch:
    build:
      context: .
      dockerfile: Dockerfile.batch
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_ENVIRONMENTS_COUNT=0

  envelope:
    build:
      context: .
      dockerfile: Dockerfile.envelope
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=development
      - VITE_ENVIRONMENTS_COUNT=0
